### ISSUE TITLE
.net 4.7.2 support

### ISSUE THREAD

**Issue by Poltergeisen** [Sebazzz/SystemWebpack#4]
Does this work with .net 4.7.2? Is it needed or did microsoft implement something themselves?

Also... this works with angular CLI as well, right?

**Comment by Sebazzz** [comment]
> Does this work with .net 4.7.2? Is it needed or did microsoft implement something themselves?

That is the whole point of this library, bring the Webpack goodness of .NET Core to .NET Framework (System.Web projects).

> Also... this works with angular CLI as well, right?

It interfaces with webpack. If you want to interface with Angular, you'Il have to extend this library.

**Comment by Poltergeisen** [comment]
I think the issue I had is that the nuget package isn't showing up in nuget. I think the problem is because it's not targeting .net 4.7.

I could be wrong though

**Comment by Sebazzz** [comment]
It is pre-release (beta). Nuget always considers packages to be forward compatible, and always shows the package, even it cannot be installed.

**Comment by Poltergeisen** [comment]
Ahh I see, I must not have had the prerelease checkbox on. Sorry about that!
